function omegaPrime = GetOmegaPrime(x, penaltyIdxList, Cvar, alpha, CnegaList, clampSize)

omega = 0;
for jj = 1:length(x)
    omega = omega + (GetCValue(x, jj-2, CnegaList, clampSize) - ...
                     4*GetCValue(x, jj-1, CnegaList, clampSize) + ...
                     6*GetCValue(x, jj, CnegaList, clampSize) - ...
                     4*GetCValue(x, jj+1, CnegaList, clampSize) + ...
                     GetCValue(x, jj+2, CnegaList, clampSize))^2;
end
omegaPrime = omega + alpha * sum((Cvar(penaltyIdxList) - x(penaltyIdxList)) .^2);
end